# Generated by Django 4.2.6 on 2023-11-06 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("descricao", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=128)),
                ("numPeriodos", models.IntegerField()),
                ("chMinima", models.IntegerField()),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.area"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=128)),
                ("carga", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Pergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pergunta", models.CharField(max_length=200)),
                ("exatas", models.IntegerField(default=0)),
                ("biologicas", models.IntegerField(default=0)),
                ("engenharias", models.IntegerField(default=0)),
                ("saude", models.IntegerField(default=0)),
                ("agrarias", models.IntegerField(default=0)),
                ("linguistica", models.IntegerField(default=0)),
                ("sociais", models.IntegerField(default=0)),
                ("humanas", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Resultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exatas", models.IntegerField(default=0)),
                ("biologicas", models.IntegerField(default=0)),
                ("engenharias", models.IntegerField(default=0)),
                ("saude", models.IntegerField(default=0)),
                ("agrarias", models.IntegerField(default=0)),
                ("linguistica", models.IntegerField(default=0)),
                ("sociais", models.IntegerField(default=0)),
                ("humanas", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelacaoDisciplinas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo", models.IntegerField()),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.curso"
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.disciplina"
                    ),
                ),
            ],
        ),
    ]
