# Generated by Django 4.2.6 on 2023-11-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('opcao_1', models.CharField(default='Nada interessado', editable=False)),
                ('opcao_2', models.CharField(default='Pouco interessado', editable=False)),
                ('opcao_3', models.CharField(default='Neutro', editable=False)),
                ('opcao_4', models.CharField(default='Interessado', editable=False)),
                ('opcao_5', models.CharField(default='Muito interessado', editable=False)),
            ],
        ),
    ]
