# Generated by Django 4.2.6 on 2023-10-21 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="cargaTotal",
        ),
    ]
