# Generated by Django 4.2.6 on 2023-10-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_curso_cargatotal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
