# Generated by Django 4.2.6 on 2023-10-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_curso_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="chMinima",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="relacaodisciplinas",
            name="periodo",
            field=models.IntegerField(),
        ),
    ]
